default_language_version:
  python: python3.9
repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      args: [--safe, --quiet]
      exclude: docs/examples/
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: [ "--application-directories=.:src" , --py38-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    - id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.1.0"
  hooks:
    - id: pyproject-fmt
      exclude: docs/examples/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        args: [--strict]
        language_version: "3.10"
        additional_dependencies:
            - types-setuptools
            - tokenize-rt==3.2.0
            - pytest == 7.1
            - importlib_metadata
            - typing-extensions>=4.5
            - rich
